config/routes.rb
Rails.application.routes.draw do

  
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'signup', to: 'users#signup'
  resources :users, except:[:new]
  
  resources :articles

end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  validates :title, presence: true, length: {minimum:3, maximum:10}
  validates :desc, presence:true, length: {minimum:10, maximum:300}
  validates :user_id, presence:true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  validates :username, presence: true, length: {minimum:3, maximum:25}, uniqueness: {case_sensitive: false}
  VALID_EMAIL_REGEX=/\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: {maximum:105}, uniqueness: {case_sensitive:false}, format:{with: VALID_EMAIL_REGEX}
  has_secure_password  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.paginate(page: params[:page], per_page:5);
  end
  def new
    @article = Article.new
  end
  def edit
    @article = Article.find(params[:id])
  end
  def create 
    @article = Article.new(article_params)
    @article.user=User.first
    if @article.save
      flash[:success] = "Article was successfully created"
      # redirect to show template
      redirect_to article_path(@article)
    else
      render 'new'
    end
  end
  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      flash[:success] = "Article was updated"
      redirect_to article_path(@article)
    else
      render 'edit'
    end
  end
  
  def show
    @article = Article.find(params[:id])
  end
  
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    flash[:danger] = "Article was deleted."
    redirect_to articles_path
  end
  
  private
  def article_params
    params.require(:article).permit(:title,:desc)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
  def about
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def signup
    @user = User.new
  end
  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success]="Welcome to alpha blog #{@user.username}"
      redirect_to users_path
    else
      render 'signup'
    end
  end
  
  def index
    @users= User.paginate(page:params[:page], per_page:2)
  end
  
  def edit
    @user = User.find(params[:id])
  end
  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      flash[:success]="User was updated successfully"
      redirect_to users_path
    else
      render 'edit'
    end
  end
  
  def destroy
    @user = User.find(params[:id])
    @user.destroy
    flash[:success]="User was deleted"
    redirect_to users_path
  end
  
  def show
    @user = User.find(params[:id])
  end
  
  private
  def user_params
    params.require(:user).permit(:username,:email,:password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/articles/_article.html.erb
<% obj.each do |article| %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      
      <div class="article-title">
        <%= link_to article.title, article_path(article) %>
        <div class="article-meta-details">
          <h6>
            Created by: <%= article.user.username if article.user %>
          </h6>
        </div>
      </div>
      
      <div class="article-body">
        <%= article.desc %>  
      </div>

      <hr>
      <%= link_to 'Edit', edit_article_path(article), class:"btn btn-xs btn-primary" %>
      <%= link_to 'Delete',article_path(article), method: :delete, data: {confirm: "Are you sure ?"}, class:"btn btn-xs btn-danger"  %>

      
    </div>
  </div>
</div>
<% end %>

app/views/articles/_form.html.erb
<%= render 'shared/errors', obj: @article %>


<div class="row">
  <div class="col-xs-12">

    <%= form_for(@article, :html => {class:"form-horizontal", role:"form"}) do |f| %>
    
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :title %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :title, class:"form-control", placeholder:"Title of article", autofocus: true %>
      </div>
    </div>
        
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :desc %>
      </div>
      <div class="col-sm-8">
        <%= f.text_area :desc, rows:10, class:"form-control", placeholder:"Body of article" %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit class:"btn btn-primary btn-lg" %>  
      </div>
    </div>
    
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to 'Cancel request and return to index', articles_path %> ]
    </div>

</div>
</div>

app/views/articles/edit.html.erb
<h1 align="center"> Edit the article. </h1>

<!-- We call the common code in _form.html.erb as below -->
<%= render 'form' %>

app/views/articles/index.html.erb
<h2>  All Articles </h2>

<div class='center'>
  <%= will_paginate %>
</div>

<%= render 'article', obj: @articles %>

<div class='center'>
  <%= will_paginate %>
</div>

app/views/articles/new.html.erb
<h1 align="center"> Create an article. </h1>

<!-- We call the common code in _form.html.erb as below -->
<%= render 'form' %>

app/views/articles/show.html.erb
<h2> <strong> <%= @article.title %> <strong> </h2>

<div class="row">
  <div class="col-xs-8">
    <h4> <strong> Description </strong> </h4>
    <hr>
    <%= simple_format(@article.desc) %>
    <hr>
    
    <%= link_to 'Edit this aticle', edit_article_path(@article), class:'btn btn-xs btn-primary' %>
    <%= link_to 'Delete this article', article_path(@article), method: :delete, class:'btn btn-xs btn-danger', data: {confirm:"Sure ?"} %>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="footer">
    <small>
      Copyright &copy;
    </small>
    <li> <%= link_to "About", about_path %>  </li>
  </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="row">
  <div class="col-xs-10 col-xs-offset-1">
    <% flash.each do |name,msg| %>
    <div class='alert alert-<%="#{name}" %>'>
      <a href="#" class="close" data-dismiss="alert"> &#215 </a>
      <%= content_tag :div, msg, :id => "flash_#{name}" if msg.is_a?(String) %>
    </div>
    <% end %>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Alpha-blog", root_path, class:"navbar-brand", id:"logo" %>
      
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li> <%= link_to 'Articles', articles_path %> </li>
        <li> <%= link_to 'Users', users_path %> </li>
        <li> <%= link_to 'Create', new_article_path %> </li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Actions <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li> <%= link_to 'New Article', new_article_path %> </li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul>
        </li>
      </ul>
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AlphaBlog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render 'layouts/navigation' %>
<%= render 'layouts/messages' %>

<div class="container">
  <%= yield %>
</div>

<%= render 'layouts/footer'%>

</body>
</html>

app/views/pages/about.html.erb
<!DOCTYPE html>

<html>
<body style="font-family:verdana">

<h1> About Us </h1>
<hr>

<ul style="list-style-type:square">
  <li> NM  </li>
  <li> KP </li>
</ul>

<hr>
<%= link_to 'Home', root_path %>
<hr>
<h3 style="text-align:center; font-size:80%"> <sup>@</sup>Copryight <h3>

</body>
</html>

app/views/pages/home.html.erb
<div class="center jumbotron">

<h1> Welcome to alpha-blog </h1>

<%= link_to 'Sign up now', signup_path, class: "btn btn-danger btn-lg btn-xlarge" %>

</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>

<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h2 class="panel-title">
          <%= pluralize(obj.errors.count,"error") %>
          prohibited article from saving
        </h2>
        <div class="panel-body">
          <ul>
            <%= obj.errors.full_messages.each do |msg| %>
            <li> <%= msg %> </li>
            <% end %>
          <ul>
        </div>
      </div>
    </div>
  </div>
</div>

<% end %>

app/views/users/_form.html.erb
<%= render 'shared/errors', obj: @user %>


<div class="row">
  <div class="col-xs-12">

    <%= form_for(@user, :html => {class:"form-horizontal", role:"form"}) do |f| %>
    
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :username %>
      </div>
      <div class="col-sm-8">
        <%= f.text_field :username, class:"form-control", placeholder:"Username", autofocus: true %>
      </div>
    </div>
        
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :email %>
      </div>
      <div class="col-sm-8">
        <%= f.email_field :email, rows:10, class:"form-control", placeholder:"Your email" %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="control-label col-sm-2">
        <%= f.label :password %>
      </div>
      <div class="col-sm-8">
        <%= f.password_field :password, rows:10, class:"form-control", placeholder:"Your password" %>
      </div>
    </div>
    
    <div class="form-group">
      <div class="col-sm-offset-2 col-sm-10">
          <%= f.submit(@user.new_record? ? 'Signup' : 'Edit', class:"btn btn-primary btn-lg") %>
      </div>
    </div>
    
    <% end %>
    <div class="col-xs-4 col-xs-offset-4">
      [ <%= link_to 'Cancel request and return to index', articles_path %> ]
    </div>

</div>
</div>

app/views/users/edit.html.erb
<h2> Edit the user details. </h2>
<%= render 'form' %>

app/views/users/index.html.erb
<h2> List of all users </h2>

<div class='center'>
  <%= will_paginate %>
</div>

<% @users.each do |user| %>
<div class="row">
  <div class="col-xs-8 col-xs-offset-2">
    <div class="well well-lg">
      
      <div class="article-title">
        <%= link_to user.username, user_path(user) %>
      </div>
      
      <div class="article-body">
        <%= user.email %>  
      </div>

      <hr>
      <%= link_to 'Edit', edit_user_path(user), class:"btn btn-xs btn-primary" %>
      <%= link_to 'Delete',user_path(user), method: :delete, data: {confirm: "Are you sure ?"}, class:"btn btn-xs btn-danger"  %>

      
    </div>
  </div>
</div>

<% end %>

<div class='center'>
  <%= will_paginate %>
</div>

app/views/users/show.html.erb
<h2> Articles by the user </h2>
<%= @user.username %>
Article
<%= render 'articles/article', obj: @user.articles %>

app/views/users/signup.html.erb
<h2> New user Signup </h2>
<%= render 'form' %>